In [1]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import pickle




from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR, SVC, LinearSVC, LinearSVR
from sklearn.metrics import accuracy_score
from tqdm import tqdm


In [18]:
df = []
path = []
label = []
fns = [i for i in os.listdir('data/gesture') if 'from' in i]

for i in fns:
    path_tmp = ['data/gesture' + '/' + i + '/' + j for j in os.listdir('data/gesture' + '/' + i)]
    path.append(path_tmp)

def load_data(path):
    data = pd.read_csv(path, sep = ',', header=None)
    data.columns = ['time', 'sensor1', 'sensor2', 'sensor3', 'sensor4', 'label']
    print(path)
    data[['label']] = data[['label']].astype(int)
    return data

def extract_label(path):
    num = path.split("/")[2][0]
    return int(num)

for i in range(0, len(path)):
    for j in path[i]:
        df.append(load_data(j))
        label.append(extract_label(j))

data/gesture/2_from3to2_4to1/45.csv
data/gesture/2_from3to2_4to1/25.csv
data/gesture/2_from3to2_4to1/19.csv
data/gesture/2_from3to2_4to1/32.csv
data/gesture/2_from3to2_4to1/10.csv
data/gesture/2_from3to2_4to1/55.csv
data/gesture/2_from3to2_4to1/30.csv
data/gesture/2_from3to2_4to1/54.csv
data/gesture/2_from3to2_4to1/41.csv
data/gesture/2_from3to2_4to1/20.csv
data/gesture/2_from3to2_4to1/16.csv
data/gesture/2_from3to2_4to1/40.csv
data/gesture/2_from3to2_4to1/6.csv
data/gesture/2_from3to2_4to1/43.csv
data/gesture/2_from3to2_4to1/18.csv
data/gesture/2_from3to2_4to1/46.csv
data/gesture/2_from3to2_4to1/47.csv
data/gesture/2_from3to2_4to1/7.csv
data/gesture/2_from3to2_4to1/4.csv
data/gesture/2_from3to2_4to1/39.csv
data/gesture/2_from3to2_4to1/34.csv
data/gesture/2_from3to2_4to1/50.csv
data/gesture/2_from3to2_4to1/28.csv
data/gesture/2_from3to2_4to1/11.csv
data/gesture/2_from3to2_4to1/24.csv
data/gesture/2_from3to2_4to1/44.csv
data/gesture/2_from3to2_4to1/14.csv
data/gesture/2_from3to2_4to1/42

data/gesture/1_from1to2_4to3/34.csv
data/gesture/1_from1to2_4to3/28.csv
data/gesture/1_from1to2_4to3/11.csv
data/gesture/1_from1to2_4to3/24.csv
data/gesture/1_from1to2_4to3/44.csv
data/gesture/1_from1to2_4to3/14.csv
data/gesture/1_from1to2_4to3/42.csv
data/gesture/1_from1to2_4to3/37.csv
data/gesture/1_from1to2_4to3/12.csv
data/gesture/1_from1to2_4to3/26.csv
data/gesture/1_from1to2_4to3/38.csv
data/gesture/1_from1to2_4to3/17.csv
data/gesture/1_from1to2_4to3/36.csv
data/gesture/1_from1to2_4to3/1.csv
data/gesture/1_from1to2_4to3/35.csv
data/gesture/1_from1to2_4to3/9.csv
data/gesture/1_from1to2_4to3/22.csv
data/gesture/1_from1to2_4to3/23.csv
data/gesture/1_from1to2_4to3/13.csv
data/gesture/1_from1to2_4to3/27.csv
data/gesture/1_from1to2_4to3/8.csv
data/gesture/1_from1to2_4to3/5.csv
data/gesture/1_from1to2_4to3/31.csv
data/gesture/1_from1to2_4to3/2.csv
data/gesture/1_from1to2_4to3/21.csv
data/gesture/1_from1to2_4to3/15.csv
data/gesture/1_from1to2_4to3/29.csv
data/gesture/1_from1to2_4to3/33.c

# data prepare

In [19]:
x=np.linspace(0, 99, 100)
# print(x)
def scaling(np_array):
    length = len(np_array)
    xp = np.linspace(0, length, length)
    xp = xp*100/length
    xp = xp.astype(int)

    y = np.interp(x, xp, np_array)
    y = y.astype(int)
    return y

def pd_to_np(df0):
    sen1 = scaling(df0['sensor1'])
    sen2 = scaling(df0['sensor2'])
    sen3 = scaling(df0['sensor3'])
    sen4 = scaling(df0['sensor4'])
    sensor = np.array((sen1, sen2, sen3, sen4))

    return sensor

In [20]:
dataset = []
for i in range(len(df)):
    tmp = pd_to_np(df[i])
#     tmp = np.reshape(tmp, 400)
    dataset.append(tmp)



In [21]:
# extract max index:
new_dataset = []
for i in range(len(dataset)):
    tmp = np.argmax(dataset[i], axis=1)
    new_dataset.append(tmp)

In [22]:
new_dataset = np.array(new_dataset)
label = np.array(label)
label = np.reshape(label, (len(df), 1))


In [23]:
Data_label = np.hstack((new_dataset, label))
# Data_label = np.concatenate((new_dataset,label),axis=1)

In [24]:
Data_label[0:100, :]

array([[66, 62, 37, 33,  2],
       [84, 71, 59, 59,  2],
       [72, 55, 48, 41,  2],
       [85, 57, 46, 39,  2],
       [70, 40, 45, 40,  2],
       [75, 55, 37, 37,  2],
       [76, 44, 34, 36,  2],
       [72, 52, 38, 36,  2],
       [62, 51, 37, 37,  2],
       [75, 62, 50, 41,  2],
       [68, 57, 45, 42,  2],
       [64, 53, 46, 28,  2],
       [84, 60, 47, 47,  2],
       [60, 50, 40, 33,  2],
       [75, 54, 36, 27,  2],
       [60, 53, 42, 42,  2],
       [76, 64, 56, 40,  2],
       [67, 54, 45, 45,  2],
       [93, 66, 60, 63,  2],
       [69, 56, 52, 43,  2],
       [78, 59, 43, 43,  2],
       [69, 56, 34, 30,  2],
       [70, 50, 40, 40,  2],
       [69, 50, 50, 46,  2],
       [76, 60, 48, 56,  2],
       [69, 52, 43, 30,  2],
       [60, 52, 44, 44,  2],
       [70, 59, 40, 37,  2],
       [64, 45, 41, 35,  2],
       [72, 64, 52, 56,  2],
       [62, 27, 41, 44,  2],
       [75, 65, 50, 40,  2],
       [50, 50, 32, 32,  2],
       [75, 60, 53, 50,  2],
       [73, 50

In [25]:
np.random.shuffle(Data_label)
# print(Data_label[:, -1])
Data = Data_label[:, :-1]
label = Data_label[:, -1]
print(label)

[3 4 5 1 5 3 4 3 3 6 1 5 5 4 5 6 4 6 5 3 1 1 3 6 2 3 5 6 5 5 4 4 5 4 6 2 6
 2 1 4 3 4 5 2 4 6 1 5 5 1 1 1 3 4 4 4 4 2 6 4 1 1 2 2 1 4 2 2 4 4 5 5 1 5
 1 4 3 3 3 4 2 3 6 6 2 3 6 2 6 5 6 6 1 5 5 6 6 3 3 5 2 3 2 6 2 4 1 3 3 1 5
 6 2 6 2 1 2 5 1 5 1 6 5 4 5 6 4 3 3 4 6 3 2 4 6 2 4 4 6 2 5 2 4 1 3 6 6 1
 4 6 1 2 1 4 1 2 6 3 4 3 4 1 5 4 3 4 2 5 2 3 4 5 3 2 1 5 2 4 3 4 4 2 5 4 6
 1 6 4 5 2 6 5 3 1 1 2 4 3 5 2 5 4 5 6 6 5 2 4 2 2 3 4 6 6 5 2 4 1 3 1 4 5
 2 3 4 5 1 3 5 4 6 5 4 3 6 2 5 1 6 3 6 6 2 4 5 1 5 6 5 4 1 6 1 3 6 2 6 1 3
 3 5 6 6 2 3 4 4 3 3 1 3 2 3 5 5 3 4 1 2 1 2 2 2 5 2 3 3 1 3 4 4 3 4 5 4 2
 6 3 1 4 3 2 4 2 5 3 6 5 2 3 1 5 3 2 5 5 2 2 2 3 1 6 1 5 6 5]


In [26]:
Data

array([[31, 29, 45, 64],
       [61, 65, 53, 42],
       [39, 51, 60, 71],
       ...,
       [55, 70, 79, 32],
       [60, 48, 91, 88],
       [34, 44, 51, 48]])

# Model

In [27]:
X_train, X_test, y_train, y_test = train_test_split(Data, label)

In [28]:
ln = RandomForestClassifier()
ln.fit(X_train, y_train)
pred = ln.predict(X_test)
accuracy_score(y_test, pred)

0.7317073170731707

In [29]:
ln = ExtraTreesClassifier()
ln.fit(X_train, y_train)
pred = ln.predict(X_test)
accuracy_score(y_test, pred)

0.8414634146341463

In [30]:
ln = SVC()
ln.fit(X_train, y_train)
pred = ln.predict(X_test)
accuracy_score(y_test, pred)

0.8414634146341463

In [32]:
pred

array([3, 6, 3, 4, 6, 3, 4, 6, 5, 5, 6, 4, 6, 3, 6, 4, 5, 4, 1, 6, 3, 3,
       4, 4, 6, 6, 1, 5, 2, 4, 3, 1, 5, 3, 4, 4, 5, 4, 1, 4, 1, 6, 2, 3,
       2, 4, 3, 6, 2, 1, 3, 6, 4, 6, 6, 6, 1, 3, 3, 3, 2, 1, 2, 3, 4, 3,
       4, 3, 5, 3, 2, 6, 6, 4, 4, 6, 2, 2, 5, 3, 6, 5])

In [33]:
y_test

array([3, 6, 3, 5, 1, 6, 4, 6, 5, 5, 6, 4, 6, 3, 6, 4, 5, 4, 1, 6, 3, 6,
       4, 4, 6, 6, 1, 1, 2, 4, 3, 1, 5, 3, 4, 4, 5, 4, 1, 4, 5, 6, 2, 3,
       2, 4, 3, 6, 2, 5, 3, 6, 6, 6, 6, 6, 5, 3, 3, 3, 2, 1, 2, 3, 4, 3,
       6, 6, 1, 3, 2, 6, 6, 2, 4, 6, 2, 2, 5, 3, 6, 5])